### ISSUE TITLE
Bug: The tray icon has a hard to see color on the gnome desktop

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [cscarney/syndic#100]
The tray icon of the app on the gnome desktop is hard to use as it uses a color that makes it close to invisible. It should use a lighter color to make it more visible. A setting in the app to switch the color of the icon manually would help a lot when the automatic detection does not work as expected.

I am using the app as a Flatpak on Gnome 43 with Fedora 37. The tray icons are rendered by the AppIndicator and KStatusNotifierItem Support extension:

https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by cscarney** [comment]
I can confirm this on GNOME 43.1 in Ubuntu Kinetic.

I don't think it's feasible to offer this as an application setting; the icon comes from the system icon theme with the color already applied. I can look into why it's getting the wrong color on GNOME, though. Other KDE apps seem to get the correct color on their tray icons, so this should be fixable.
