### ISSUE TITLE
empty screen on Android

### ISSUE THREAD

**Issue by cecxl** [cscarney/syndic#138]
Installed this on Redmi Note 8 pro, after the logo just empty screen along with keyboard appear instead of the UI.

**Comment by cscarney** [comment]
I was able to reproduce this on an 8" Galaxy Tab S2. When the feed list is empty (no feeds configured) *and* the device is in portrait mode when the application is launched, it should show the "Add Content" page but it shows an empty page row instead.

If you force stop the application and relaunch it with the device in the landscape orientation, does the issue go away?

**Comment by cscarney** [comment]
[This update](https://github.com/cscarney/syndic/releases/tag/v1.3.2) should fix the problem.
