### ISSUE TITLE
Please consider submitting this project to SaaS (“Hosted”) Weblate for ease of maintenance of translations

### ISSUE THREAD

**Issue by fitojb** [cscarney/syndic#2]
It’s much faster for contributors to use an online platform than building each project and submitting PRs :)

I suggest hosted.weblate.org because it’s free software, but Crowdin would also work, personally :)

**Comment by cscarney** [comment]
I set up a trial project on weblate at https://hosted.weblate.org/projects/syndic/app/

**Comment by cscarney** [comment]
Weblate has approved us!
