### ISSUE TITLE
Touch screen: article list highlight not cleared after long-press

### ISSUE THREAD

**Issue by plata** [cscarney/syndic#75]
How to:
- select article
- press (long click) other article(s)

Now, both articles are selected. If clicking (short) another article, the pressed article also stays selected.

Same behavior in the feed list.

When trying to reproduce the behavior with a mouse, the first article looses it's selection when releasing the press on the second article.

**Comment by cscarney** [comment]
QML ListView doesn't really have any native support for multiple selection, and I'm not aware of any other QML apps that support it.

It would be *possible* to implement some sort of multi-select mode from scratch if there's a good reason to, but for what purpose?  We have a master-detail pattern in which all of the per-article functions are in the detail view.  What would you expect to happen if you had multiple articles selected?

**Comment by plata** [comment]
I do not want to have multi selection. The multi selection happens with the current implementation (and it shouldn't).

**Comment by cscarney** [comment]
Sorry, I misunderstood.  Yes, that is a bug.

I think that this is an issue with highlighting and not selection. The selection changes when the click is release; the list item uses the highlighted appearance both for the selected item, and during a click in progress.  That's Kirigami's default list item behavior, but it looks like something we're doing on long-press is preventing the highlight from being cleared.

**Comment by cscarney** [comment]
This seems to be fixed on Qt6 with the fix for [this Qt bug](https://bugreports.qt.io/browse/QTBUG-62912) in 6.5.3.
