### ISSUE TITLE
Add option to hide read articles immediately

### ISSUE THREAD

**Issue by plata** [cscarney/syndic#96]
Currently, the article stays in the list.

**Comment by cscarney** [comment]
I'm not going to add these kinds of UI tweaks at this time.  I want to focus on the default UX until the core product is more mature.  

Removing items from the list as you open them is something I tried and rejected before settling on the current behavior.  I feel very strongly that navigating forward-then-back should leave you in the same place where you started, and separating the feed list from the navigation stack would be needlessly complex.

I might reconsider this at some point in the future, but for now I have to veto this one.
