### ISSUE TITLE
Feature: Add option to start syndic in background on login

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [cscarney/syndic#99]
I am currently trying out syndic and like its simple to use interface. One feature that I am missing currently is the ability to start it minimized on login. This would allow syndic to fetch feeds right after login and would make it more comfortable for desktop users.

I am using the app as a Flatpak on Gnome 43 with Fedora 37.

**Comment by cscarney** [comment]
Implemented in a44f20d5ba5404870c26e7672fe0aba217b477d2
